import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  TextInput,
  SafeAreaView,
} from 'react-native';
import { useNavigation } from '@react-navigation/native';
import Categories from '../components/categories';
import Recipes from '../components/recipes';

const categories = [
  { idCategory: '1', strCategory: 'Beef', strCategoryThumb: 'https://www.themealdb.com/images/category/beef.png' },
  { idCategory: '2', strCategory: 'Chicken', strCategoryThumb: 'https://www.themealdb.com/images/category/chicken.png' },
  { idCategory: '3', strCategory: 'Dessert', strCategoryThumb: 'https://www.themealdb.com/images/category/dessert.png' },
  { idCategory: '4', strCategory: 'Lamb', strCategoryThumb: 'https://www.themealdb.com/images/category/lamb.png' },
  { idCategory: '5', strCategory: 'Miscellaneous', strCategoryThumb: 'https://www.themealdb.com/images/category/miscellaneous.png' },
  { idCategory: '6', strCategory: 'Pasta', strCategoryThumb: 'https://www.themealdb.com/images/category/pasta.png' },
  { idCategory: '7', strCategory: 'Pork', strCategoryThumb: 'https://www.themealdb.com/images/category/pork.png' },
  { idCategory: '8', strCategory: 'Seafood', strCategoryThumb: 'https://www.themealdb.com/images/category/seafood.png' },
  { idCategory: '9', strCategory: 'Side', strCategoryThumb: 'https://www.themealdb.com/images/category/side.png' },
  { idCategory: '10', strCategory: 'Starter', strCategoryThumb: 'https://www.themealdb.com/images/category/starter.png' },
  { idCategory: '11', strCategory: 'Vegan', strCategoryThumb: 'https://www.themealdb.com/images/category/vegan.png' },
  { idCategory: '12', strCategory: 'Vegetarian', strCategoryThumb: 'https://www.themealdb.com/images/category/vegetarian.png' },
  { idCategory: '13', strCategory: 'Breakfast', strCategoryThumb: 'https://www.themealdb.com/images/category/breakfast.png' },
  { idCategory: '14', strCategory: 'Goat', strCategoryThumb: 'https://www.themealdb.com/images/category/goat.png' },
];

const allRecipes = [
  {
    idMeal: '52874',
    strMeal: 'Beef and Mustard Pie',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/sytuqu1511553755.jpg',
    strCategory: 'Beef',
    strArea: 'British',
    strInstructions: 'Preheat the oven to 150C/300F/Gas 2. Toss the beef and flour together in a bowl with some salt and black pepper. Heat a large casserole until hot, add half of the rapeseed oil and enough of the beef to just cover the bottom of the casserole. Fry until browned on each side, then remove and set aside. Repeat with the remaining oil and beef. Return the beef to the pan, add the wine and cook until the volume of liquid has reduced by half, then add the stock, onion, carrots, thyme and mustard, and game to the boil. Cover with a lid and place in the oven for two hours. Remove from the oven, check the seasoning and set aside to cool. Remove the thyme. When the beef is cold and you're ready to assemble the pie, preheat the oven to 200C/400F/Gas 6. Transfer the beef to a pie dish. Brush the rim with the beaten egg yolks and lay the pastry over the top. Brush with more beaten egg.',
    strIngredient1: 'Beef',
    strIngredient2: 'Plain Flour',
    strIngredient3: 'Rapeseed Oil',
    strIngredient4: 'Red Wine',
    strIngredient5: 'Beef Stock',
    strIngredient6: 'Onion',
    strIngredient7: 'Carrots',
    strIngredient8: 'Thyme',
    strIngredient9: 'Mustard',
    strIngredient10: 'Egg Yolks',
    strMeasure1: '1kg',
    strMeasure2: '2 tbs',
    strMeasure3: '2 tbs',
    strMeasure4: '200ml',
    strMeasure5: '400ml',
    strMeasure6: '1 chopped',
    strMeasure7: '2 chopped',
    strMeasure8: '3 sprigs',
    strMeasure9: '2 tbs',
    strMeasure10: '2',
    servings: '4',
    calories: '650',
    difficulty: 'Medium',
  },
  {
    idMeal: '52878',
    strMeal: 'Beef Stroganoff',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/svprys1511176755.jpg',
    strCategory: 'Beef',
    strArea: 'Russian',
    strInstructions: 'Heat the olive oil in a large, lidded frying pan over a high heat. Add the beef strips and fry until sealed and browned all over. Remove from the pan and set aside. Add the butter to the pan, and once foaming, add the onion. Reduce the heat to medium and fry for 10 minutes until softened. Add the mushrooms and garlic, and fry for 5 minutes. Pour in the wine, bring to a simmer, then cook until the wine has reduced by half. Stir in the crème fraîche and mustard. Return the beef to the pan, season with salt and pepper, and stir well. Cover and cook for 20 minutes over low heat. Garnish with parsley and serve with rice.',
    strIngredient1: 'Beef Fillet',
    strIngredient2: 'Olive Oil',
    strIngredient3: 'Butter',
    strIngredient4: 'Onion',
    strIngredient5: 'Mushrooms',
    strIngredient6: 'Garlic',
    strIngredient7: 'White Wine',
    strIngredient8: 'Creme Fraiche',
    strIngredient9: 'Mustard',
    strIngredient10: 'Parsley',
    strMeasure1: '500g',
    strMeasure2: '2 tbs',
    strMeasure3: '25g',
    strMeasure4: '1 sliced',
    strMeasure5: '250g',
    strMeasure6: '2 cloves',
    strMeasure7: '150ml',
    strMeasure8: '200ml',
    strMeasure9: '1 tbs',
    strMeasure10: 'Handful',
    servings: '4',
    calories: '580',
    difficulty: 'Easy',
  },
  {
    idMeal: '52940',
    strMeal: 'Chicken Alfredo Primavera',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg',
    strCategory: 'Chicken',
    strArea: 'Italian',
    strInstructions: 'Cook the fettuccine according to the package directions. In a large skillet, cook the chicken in 2 tablespoons of butter until no longer pink. Remove from skillet and keep warm. In the same skillet, saute the vegetables in remaining butter until tender. Add the garlic, cook 1 minute longer. Stir in the cream, cheese, basil and pepper. Cook until cheese is melted. Add the chicken and pasta, toss to coat.',
    strIngredient1: 'Fettuccine',
    strIngredient2: 'Chicken Breast',
    strIngredient3: 'Butter',
    strIngredient4: 'Broccoli',
    strIngredient5: 'Red Pepper',
    strIngredient6: 'Garlic',
    strIngredient7: 'Heavy Cream',
    strIngredient8: 'Parmesan',
    strIngredient9: 'Basil',
    strIngredient10: 'Black Pepper',
    strMeasure1: '400g',
    strMeasure2: '500g',
    strMeasure3: '4 tbs',
    strMeasure4: '2 cups',
    strMeasure5: '1 diced',
    strMeasure6: '3 cloves',
    strMeasure7: '300ml',
    strMeasure8: '100g',
    strMeasure9: '2 tbs',
    strMeasure10: '1 tsp',
    servings: '6',
    calories: '720',
    difficulty: 'Easy',
  },
  {
    idMeal: '52846',
    strMeal: 'Chicken Enchiladas',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg',
    strCategory: 'Chicken',
    strArea: 'Mexican',
    strInstructions: 'Preheat oven to 350°F. Heat oil in a large skillet over medium heat. Add onion and cook until soft, about 5 minutes. Add garlic and cook 1 minute. Add chicken and cook until heated through. Stir in half of the enchilada sauce. Spoon mixture into tortillas and roll up. Place seam side down in a baking dish. Top with remaining sauce and cheese. Bake 20 minutes until cheese is melted and bubbly.',
    strIngredient1: 'Chicken',
    strIngredient2: 'Onion',
    strIngredient3: 'Garlic',
    strIngredient4: 'Enchilada Sauce',
    strIngredient5: 'Tortillas',
    strIngredient6: 'Cheese',
    strIngredient7: 'Oil',
    strIngredient8: 'Sour Cream',
    strIngredient9: 'Cilantro',
    strIngredient10: 'Lime',
    strMeasure1: '500g shredded',
    strMeasure2: '1 diced',
    strMeasure3: '2 cloves',
    strMeasure4: '400ml',
    strMeasure5: '8',
    strMeasure6: '200g',
    strMeasure7: '2 tbs',
    strMeasure8: 'To serve',
    strMeasure9: 'Handful',
    strMeasure10: '1',
    servings: '4',
    calories: '520',
    difficulty: 'Easy',
  },
  {
    idMeal: '52893',
    strMeal: 'Apple Frangipan Tart',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg',
    strCategory: 'Dessert',
    strArea: 'British',
    strInstructions: 'Preheat the oven to 200C/180C Fan/Gas 6. Put the flour and sugar in a large bowl and rub in the butter with your fingertips until it resembles fine breadcrumbs. Add the egg yolk and 2 tbsp cold water and mix to form a dough. Wrap in cling film and chill for 30 mins. Roll out the pastry on a lightly floured surface to line a 23cm loose-bottomed tart tin. Chill for 20 mins. Line the pastry with baking paper and fill with baking beans. Bake for 15 mins, remove the paper and beans and bake for 5 mins more.',
    strIngredient1: 'Flour',
    strIngredient2: 'Sugar',
    strIngredient3: 'Butter',
    strIngredient4: 'Egg Yolks',
    strIngredient5: 'Almonds',
    strIngredient6: 'Apples',
    strIngredient7: 'Apricot Jam',
    strIngredient8: 'Vanilla',
    strIngredient9: 'Eggs',
    strIngredient10: 'Icing Sugar',
    strMeasure1: '200g',
    strMeasure2: '75g',
    strMeasure3: '125g',
    strMeasure4: '1',
    strMeasure5: '100g ground',
    strMeasure6: '3 medium',
    strMeasure7: '3 tbs',
    strMeasure8: '1 tsp',
    strMeasure9: '2',
    strMeasure10: 'To dust',
    servings: '8',
    calories: '380',
    difficulty: 'Hard',
  },
  {
    idMeal: '52768',
    strMeal: 'Chocolate Gateau',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/tqtywx1468317395.jpg',
    strCategory: 'Dessert',
    strArea: 'French',
    strInstructions: 'Preheat the oven to 180°C/350°F/Gas 4. Grease and line two 20cm sandwich tins. Break the chocolate into pieces and melt with the butter in a heatproof bowl over hot water. Remove from the heat. Whisk the eggs and sugar together until thick and pale. Fold in the melted chocolate. Sift in the flour and fold in gently. Divide between the tins and bake for 25-30 minutes. Cool in the tins for 5 minutes, then turn out onto a wire rack.',
    strIngredient1: 'Dark Chocolate',
    strIngredient2: 'Butter',
    strIngredient3: 'Eggs',
    strIngredient4: 'Sugar',
    strIngredient5: 'Flour',
    strIngredient6: 'Cocoa Powder',
    strIngredient7: 'Cream',
    strIngredient8: 'Vanilla',
    strIngredient9: 'Raspberries',
    strIngredient10: 'Icing Sugar',
    strMeasure1: '200g',
    strMeasure2: '175g',
    strMeasure3: '4',
    strMeasure4: '175g',
    strMeasure5: '100g',
    strMeasure6: '25g',
    strMeasure7: '300ml',
    strMeasure8: '1 tsp',
    strMeasure9: 'To serve',
    strMeasure10: 'To dust',
    servings: '10',
    calories: '450',
    difficulty: 'Medium',
  },
  {
    idMeal: '52772',
    strMeal: 'Lamb Tagine',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/yuwtuu1511295751.jpg',
    strCategory: 'Lamb',
    strArea: 'Moroccan',
    strInstructions: 'Heat the oil in a large tagine or casserole. Add the lamb and brown all over. Remove and set aside. Add the onion and cook until softened. Add the garlic, ginger, and spices, cook for 1 minute. Return the lamb, add the stock, apricots, and honey. Cover and cook for 2 hours until tender. Scatter with almonds and coriander to serve.',
    strIngredient1: 'Lamb Shoulder',
    strIngredient2: 'Olive Oil',
    strIngredient3: 'Onion',
    strIngredient4: 'Garlic',
    strIngredient5: 'Ginger',
    strIngredient6: 'Cumin',
    strIngredient7: 'Cinnamon',
    strIngredient8: 'Apricots',
    strIngredient9: 'Honey',
    strIngredient10: 'Almonds',
    strMeasure1: '800g',
    strMeasure2: '3 tbs',
    strMeasure3: '2 sliced',
    strMeasure4: '3 cloves',
    strMeasure5: '2cm piece',
    strMeasure6: '2 tsp',
    strMeasure7: '1 stick',
    strMeasure8: '100g',
    strMeasure9: '2 tbs',
    strMeasure10: '50g toasted',
    servings: '6',
    calories: '580',
    difficulty: 'Medium',
  },
  {
    idMeal: '52982',
    strMeal: 'Spaghetti Bolognese',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg',
    strCategory: 'Pasta',
    strArea: 'Italian',
    strInstructions: 'Heat the oil in a large pan over medium heat. Add the onion, carrot, and celery, cook until soft. Add the garlic and cook 1 minute. Add the beef and cook until browned, breaking up with a spoon. Add the wine and cook until evaporated. Add the tomatoes, tomato paste, herbs, and stock. Simmer for 1 hour. Season and serve with spaghetti and parmesan.',
    strIngredient1: 'Spaghetti',
    strIngredient2: 'Beef Mince',
    strIngredient3: 'Onion',
    strIngredient4: 'Carrot',
    strIngredient5: 'Celery',
    strIngredient6: 'Garlic',
    strIngredient7: 'Tomatoes',
    strIngredient8: 'Red Wine',
    strIngredient9: 'Basil',
    strIngredient10: 'Parmesan',
    strMeasure1: '400g',
    strMeasure2: '500g',
    strMeasure3: '1 diced',
    strMeasure4: '1 diced',
    strMeasure5: '2 sticks',
    strMeasure6: '2 cloves',
    strMeasure7: '400g tinned',
    strMeasure8: '150ml',
    strMeasure9: 'Handful',
    strMeasure10: 'To serve',
    servings: '4',
    calories: '620',
    difficulty: 'Easy',
  },
  {
    idMeal: '52819',
    strMeal: 'Grilled Salmon',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1549542994.jpg',
    strCategory: 'Seafood',
    strArea: 'Japanese',
    strInstructions: 'Preheat grill to high. Season the salmon with salt, pepper, and a drizzle of olive oil. Place on a baking tray and grill for 4-5 minutes each side until cooked through. Meanwhile, mix the miso, mirin, and sugar. Brush over the salmon in the last minute of cooking. Serve with rice and steamed vegetables.',
    strIngredient1: 'Salmon',
    strIngredient2: 'Olive Oil',
    strIngredient3: 'Miso Paste',
    strIngredient4: 'Mirin',
    strIngredient5: 'Sugar',
    strIngredient6: 'Ginger',
    strIngredient7: 'Soy Sauce',
    strIngredient8: 'Sesame Seeds',
    strIngredient9: 'Spring Onion',
    strIngredient10: 'Rice',
    strMeasure1: '4 fillets',
    strMeasure2: '2 tbs',
    strMeasure3: '2 tbs',
    strMeasure4: '2 tbs',
    strMeasure5: '1 tbs',
    strMeasure6: '1 tsp grated',
    strMeasure7: '1 tbs',
    strMeasure8: '1 tbs',
    strMeasure9: '2 sliced',
    strMeasure10: 'To serve',
    servings: '4',
    calories: '420',
    difficulty: 'Easy',
  },
  {
    idMeal: '52913',
    strMeal: 'Vegan Buddha Bowl',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/uwxqwy1483389553.jpg',
    strCategory: 'Vegan',
    strArea: 'American',
    strInstructions: 'Preheat oven to 400°F. Toss the chickpeas with olive oil, cumin, and paprika. Roast for 25 minutes until crispy. Cook the quinoa according to package directions. Arrange bowls with quinoa, roasted chickpeas, avocado, cucumber, tomatoes, and greens. Drizzle with tahini dressing.',
    strIngredient1: 'Quinoa',
    strIngredient2: 'Chickpeas',
    strIngredient3: 'Avocado',
    strIngredient4: 'Cucumber',
    strIngredient5: 'Tomatoes',
    strIngredient6: 'Mixed Greens',
    strIngredient7: 'Tahini',
    strIngredient8: 'Lemon Juice',
    strIngredient9: 'Cumin',
    strIngredient10: 'Olive Oil',
    strMeasure1: '200g',
    strMeasure2: '400g tinned',
    strMeasure3: '2',
    strMeasure4: '1 diced',
    strMeasure5: '200g',
    strMeasure6: '100g',
    strMeasure7: '4 tbs',
    strMeasure8: '2 tbs',
    strMeasure9: '1 tsp',
    strMeasure10: '3 tbs',
    servings: '2',
    calories: '480',
    difficulty: 'Easy',
  },
  {
    idMeal: '52765',
    strMeal: 'Vegetable Stir Fry',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg',
    strCategory: 'Vegetarian',
    strArea: 'Chinese',
    strInstructions: 'Heat oil in a wok over high heat. Add the garlic and ginger, stir fry for 30 seconds. Add the vegetables in order of cooking time - carrots first, then peppers, broccoli, and finally the softer vegetables. Stir fry for 5-7 minutes. Add the soy sauce, oyster sauce, and sesame oil. Toss to coat and serve with rice.',
    strIngredient1: 'Broccoli',
    strIngredient2: 'Carrots',
    strIngredient3: 'Bell Peppers',
    strIngredient4: 'Snow Peas',
    strIngredient5: 'Garlic',
    strIngredient6: 'Ginger',
    strIngredient7: 'Soy Sauce',
    strIngredient8: 'Oyster Sauce',
    strIngredient9: 'Sesame Oil',
    strIngredient10: 'Vegetable Oil',
    strMeasure1: '200g',
    strMeasure2: '2 sliced',
    strMeasure3: '2 sliced',
    strMeasure4: '100g',
    strMeasure5: '3 cloves',
    strMeasure6: '2cm piece',
    strMeasure7: '3 tbs',
    strMeasure8: '2 tbs',
    strMeasure9: '1 tbs',
    strMeasure10: '2 tbs',
    servings: '4',
    calories: '220',
    difficulty: 'Easy',
  },
  {
    idMeal: '52895',
    strMeal: 'Pancakes',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/rwuyqx1511383174.jpg',
    strCategory: 'Breakfast',
    strArea: 'American',
    strInstructions: 'Sift the flour, baking powder, salt, and sugar into a bowl. Make a well in the center and pour in the milk, egg, and melted butter. Mix until smooth. Heat a lightly oiled griddle or frying pan over medium-high heat. Pour about 1/4 cup of batter onto the griddle. Brown on both sides and serve hot with maple syrup and berries.',
    strIngredient1: 'Flour',
    strIngredient2: 'Baking Powder',
    strIngredient3: 'Sugar',
    strIngredient4: 'Salt',
    strIngredient5: 'Milk',
    strIngredient6: 'Egg',
    strIngredient7: 'Butter',
    strIngredient8: 'Maple Syrup',
    strIngredient9: 'Berries',
    strIngredient10: 'Vanilla',
    strMeasure1: '200g',
    strMeasure2: '2 tsp',
    strMeasure3: '2 tbs',
    strMeasure4: '1/2 tsp',
    strMeasure5: '300ml',
    strMeasure6: '1',
    strMeasure7: '50g melted',
    strMeasure8: 'To serve',
    strMeasure9: 'To serve',
    strMeasure10: '1 tsp',
    servings: '4',
    calories: '350',
    difficulty: 'Easy',
  },
];

export default function HomeScreen() {
  const navigation = useNavigation();
  const [activeCategory, setActiveCategory] = useState('All');
  const [searchQuery, setSearchQuery] = useState('');

  const filteredRecipes = allRecipes.filter((recipe) => {
    const matchesCategory = activeCategory === 'All' || recipe.strCategory === activeCategory;
    const matchesSearch = recipe.strMeal.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView showsVerticalScrollIndicator={false}>
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={styles.greeting}>Hello, Foodie!</Text>
            <Text style={styles.title}>What would you like to cook?</Text>
          </View>
          <View style={styles.headerButtons}>
            <TouchableOpacity
              style={styles.iconButton}
              onPress={() => navigation.navigate('Favorites')}
            >
              <Text style={styles.iconText}>❤️</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={styles.iconButton}
              onPress={() => navigation.navigate('MyRecipes')}
            >
              <Text style={styles.iconText}>📝</Text>
            </TouchableOpacity>
          </View>
        </View>

        {/* Search Bar */}
        <View style={styles.searchContainer}>
          <Text style={styles.searchIcon}>🔍</Text>
          <TextInput
            style={styles.searchInput}
            placeholder="Search recipes..."
            placeholderTextColor="#999"
            value={searchQuery}
            onChangeText={setSearchQuery}
          />
        </View>

        {/* Categories */}
        <Categories
          categories={categories}
          activeCategory={activeCategory}
          setActiveCategory={setActiveCategory}
        />

        {/* Recipes */}
        <Recipes recipes={filteredRecipes} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF',
    paddingTop: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  greeting: {
    fontSize: 14,
    color: '#666',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 4,
  },
  headerButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconText: {
    fontSize: 20,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    marginHorizontal: 20,
    borderRadius: 12,
    paddingHorizontal: 15,
    marginBottom: 20,
  },
  searchIcon: {
    fontSize: 18,
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 14,
    fontSize: 16,
    color: '#333',
  },
});
